# Site settings
title: Android Smart WebView
email: getmgks@gmail.com
url: https://mgks.github.io/Android-SmartWebView
description: "SWV is used to develop advanced hybrid android applications just with web technologies"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  primary-light: '#ffffff'
  links: '#569e28'
  links-dark: '#488422'
  gold: '#d98900'

# Footer settings
footer: voinsource

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/infeeds
  - title: facebook
    url: https://www.facebook.com/infeeds
  - title: stack-overflow
    url: https://stackoverflow.com/questions/tagged/swv
  - title: github
    url: https://github.com/mgks

# Build settings
markdown: kramdown
permalink: pretty
